# Generated by Django 5.0.6 on 2024-05-15 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image2text_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='type',
            field=models.CharField(blank=True, choices=[('Expository_Cause_Effect', 'Expository - Cause and Effect'), ('Expository_Comparison', 'Expository - Comparison Essay'), ('Expository_Classification', 'Expository - Classification'), ('Expository_Descriptive', 'Expository - Descriptive'), ('Expository_Problem_Solution', 'Expository - Problem and Solution'), ('Expository_Process', 'Expository - Process'), ('Expository_Essay', 'Expository - Essay'), ('Expository_Anecdotal', 'Expository - Anecdotal'), ('Narrative', 'Narrative'), ('Narrative_Short_Story', 'Narrative - Short Story'), ('Narrative_Historical_Fiction', 'Narrative - Historical Fiction'), ('Narrative_Fable', 'Narrative - Fable'), ('Narrative_First_Person', 'Narrative - First Person Narrative'), ('Narrative_Epic_Poetry', 'Narrative - Epic Poetry'), ('Narrative_Memoir', 'Narrative - Memoir'), ('Narrative_Autobiography', 'Narrative - Autobiography'), ('Narrative_Fantasy', 'Narrative - Fantasy'), ('Narrative_Parable', 'Narrative - Parable'), ('Narrative_Narrative_History', 'Narrative - Narrative History'), ('Narrative_Epic', 'Narrative - Epic'), ('Persuasive', 'Persuasive'), ('Persuasive_Logos', 'Persuasive - Appeal to Reason/Logos'), ('Persuasive_Pathos', 'Persuasive - Appeal to Emotion/Pathos'), ('Persuasive_Ethos', 'Persuasive - Appeal to Character/Ethos'), ('Persuasive_Love_Letter', 'Persuasive - Love Letters'), ('Persuasive_Speech', 'Persuasive - Speeches'), ('Persuasive_Columns', 'Persuasive - Newspaper Columns'), ('Poetry', 'Poetry'), ('Poetry_Haiku', 'Poetry - Haiku'), ('Poetry_Free_Verse', 'Poetry - Free Verse'), ('Poetry_Sonnet', 'Poetry - Sonnet'), ('Poetry_Acrostic', 'Poetry - Acrostic'), ('Poetry_Villanelle', 'Poetry - Villanelle'), ('Poetry_Limerick', 'Poetry - Limerick'), ('Poetry_Ode', 'Poetry - Ode'), ('Poetry_Ballad', 'Poetry - Ballad'), ('Creative', 'Creative'), ('Creative_Script', 'Creative - Movie/TV Script'), ('Creative_Song', 'Creative - Song'), ('Creative_Short_Story', 'Creative - Short Story'), ('Creative_Memoir', 'Creative - Memoir'), ('Review', 'Review'), ('Review_Book', 'Review - Book Review'), ('Review_Movie', 'Review - Movie Review'), ('Review_TV_Show', 'Review - TV Show Review'), ('Review_Product', 'Review - Product Review'), ('Review_Travel', 'Review - Travel Review'), ('Technical', 'Technical'), ('Technical_Brochure', 'Technical - Brochure'), ('Technical_User_Guide', 'Technical - User Guide'), ('Technical_Proposal', 'Technical - Proposal'), ('Technical_Tech_Report', 'Technical - Tech Report'), ('Technical_SOP', 'Technical - Standard Operating Procedure')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_at'], name='image2text__uploade_24f59d_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user'], name='image2text__user_id_280d5b_idx'),
        ),
    ]
